---

# Any ignore directives should be uncommented in downstream projects to disable
# Dependabot updates for the given dependency. Downstream projects will get
# these updates when the pull request(s) in the appropriate skeleton are merged
# and Lineage processes these changes.

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "docker :whale:"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "github-actions :octocat:"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "javascript :coffee:"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "python :snake:"
