---

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "docker :whale:"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "github-actions :octocat:"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "javascript :coffee:"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "python :snake:"
