version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - FOUNDRY_PASSWORD=<your_password>
      - FOUNDRY_USERNAME=<your_username>
      - FOUNDRY_ADMIN_KEY=atropos
      # - FOUNDRY_RELEASE_URL=<temporary_url>
      # - FOUNDRY_AWS_CONFIG=
      # - FOUNDRY_GID=foundry
      # - FOUNDRY_HOSTNAME=
      # - FOUNDRY_NO_UPDATE=true
      # - FOUNDRY_PROXY_PORT=
      # - FOUNDRY_PROXY_SSL=false
      # - FOUNDRY_ROUTE_PREFIX=
      # - FOUNDRY_SSL_CERT=
      # - FOUNDRY_SSL_KEY=
      # - FOUNDRY_UID=foundry
      # - FOUNDRY_UPDATE_CHANNEL=release
      # - FOUNDRY_UPNP=false
      # - FOUNDRY_VERSION=0.6.4
      # - FOUNDRY_WORLD=
      # - TIMEZONE=US/Eastern
    ports:
      - target: "30000"
        published: "30000"
        protocol: tcp
        mode: host
