---
version: "3.8"

# This docker-compose file is used to build and test the container with pytest
services:
  foundry:
    # Run the container normally
    image: felddy/foundryvtt:0.7.3
    hostname: felddy_foundryvtt
    init: true
    restart: "no"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - CONTAINER_VERBOSE=true
      - FOUNDRY_ADMIN_KEY=atropos
      - FOUNDRY_GID=foundry
      - FOUNDRY_PASSWORD  # pass through
      - FOUNDRY_UID=foundry
      - FOUNDRY_USERNAME  # pass through
      - TIMEZONE=US/Eastern
    ports:
      - target: "30000"
        published: "30001"
        protocol: tcp
        mode: host

  foundry-version:
    # Run the container to collect version information
    image: felddy/foundryvtt:0.7.3
    init: true
    restart: "no"
    command: --version
