---
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    init: true
    restart: "no"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - FOUNDRY_PASSWORD=<your_password>
      - FOUNDRY_USERNAME=<your_username>
      - FOUNDRY_ADMIN_KEY=atropos
      # - CONTAINER_CACHE=/data/container_cache
      # - CONTAINER_PATCHES=/data/container_patches
      # - CONTAINER_VERBOSE=true
      # - FOUNDRY_AWS_CONFIG=
      # - FOUNDRY_GID=foundry
      # - FOUNDRY_HOSTNAME=
      # - FOUNDRY_LICENSE_KEY=
      # - FOUNDRY_PROXY_PORT=
      # - FOUNDRY_PROXY_SSL=false
      # - FOUNDRY_RELEASE_URL=
      # - FOUNDRY_ROUTE_PREFIX=
      # - FOUNDRY_SSL_CERT=
      # - FOUNDRY_SSL_KEY=
      # - |
      #   FOUNDRY_TURN_CONFIGS=[{
      #   "url": "turn:example.com:3478",
      #   "urls": ["turn:example.com:3478", "turns:example.com:5349"],
      #   "username": "my username",
      #   "credential": "my password"
      #   }]
      # - FOUNDRY_UID=foundry
      # - FOUNDRY_UPDATE_CHANNEL=release
      # - FOUNDRY_UPNP=false
      # - FOUNDRY_VERSION=0.7.5
      # - FOUNDRY_WORLD=
      # - TIMEZONE=US/Eastern
    ports:
      - target: "30000"
        published: "30000"
        protocol: tcp
        mode: host
