---
blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Questions / Help
    url: https://github.com/felddy/foundryvtt-docker/discussions
    about: Ask questions and get help from the repository discussions
  - name: ğŸ® FoundryVTT Discord
    url: https://discord.gg/foundryvtt
    about: Visit the official FoundryVTT Discord server
  - name: ğŸµ FoundryVTT issue tracker
    url: https://github.com/foundryvtt/foundryvtt/issues
    about: Visit the official FoundryVTT issue tracker
