---

name: config

on:
  workflow_call:
    inputs:
      platforms:
        description: "The platforms to build (CSV)"
        default: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        required: false
        type: string
    outputs:
      image_name:
        description: "The Docker image name"
        value: felddy/foundryvtt
      data_artifact_name:
        description: "The name of the test data artifact"
        value: test-output
      data_artifact_path:
        description: "The path to include in the test data artifact"
        value: data
      image_archive_artifact_name:
        description: "The name of the image archives artifact"
        value: image-archives
      platforms:
        description: "The platforms to build (CSV)"
        value: ${{ inputs.platforms }}
      platforms_json:
        description: "The platforms to build (JSON)"
        value: ${{ jobs.csv-to-json.outputs.platforms_json }}
      test_platform:
        description: "The platform to use for testing"
        value: linux/amd64

jobs:
  diagnostics:
    name: "Diagnostics"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: block
          allowed-endpoints: >
            www.githubstatus.com:443

      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@8d1f141b985510f36a0376b75b4dc8b0cfc90e8a
        with:
          overall_threshold: major
          packages_threshold: major_outage

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@516dbb0c760f39b4cdd750ae095f1688780f68f4

  csv-to-json:
    name: "Convert platforms CSV to JSON"
    runs-on: ubuntu-latest
    outputs:
      platforms_json: ${{ steps.csv-to-json.outputs.platforms_json }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: block
          allowed-endpoints: >

      - name: Convert CSV to JSON
        id: csv-to-json
        run: |
          echo "platforms_json=$(echo -n ${{ inputs.platforms }} | jq --raw-input --compact-output 'split(",")')" >> $GITHUB_OUTPUT
