---
name: lint

on:
  workflow_call:
    inputs:
      buildx_cache_dir:
        default: ~/.cache/buildx
        required: false
        type: string
      curl_cache_dir:
        default: ~/.cache/curl
        required: false
        type: string
      pip_cache_dir:
        default: ~/.cache/pip
        required: false
        type: string
      pre_commit_cache_dir:
        default: ~/.cache/pre-commit
        required: false
        type: string
      go_version:
        default: '1.16'
        required: false
        type: string
      python_version:
        default: '3.9'
        required: false
        type: string
      shfmt_version:
        default: 'v3.4.3'
        required: false
        type: string

env:
  PIP_CACHE_DIR: ${{ inputs.pip_cache_dir }}
  PRE_COMMIT_CACHE_DIR: ~/.cache/pre-commit

jobs:
  lint:
    # Checks out the source and runs pre-commit hooks.  Detects coding errors
    # and style deviations.
    name: "Lint sources"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:
          # TODO: change to 'egress-policy: block' after couple of runs
          egress-policy: audit
      - id: setup-python
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984
        with:
          python-version: ${{ inputs.python_version }}
      # We need the Go version and Go cache location for the actions/cache step,
      # so the Go installation must happen before that.
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
        with:
          go-version: ${{ inputs.go_version }}
      - name: Store installed Go version
        id: go-version
        run: |
          echo "::set-output name=version::"\
          "$(go version | sed 's/^go version go\([0-9.]\+\) .*/\1/')"
      - name: Lookup Go cache directory
        id: go-cache
        run: |
          echo "::set-output name=dir::$(go env GOCACHE)"
      - uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        env:
          BASE_CACHE_KEY: "${{ github.job }}-${{ runner.os }}-\
            py${{ inputs.python_version }}-\
            go${{ steps.go-version.outputs.version }}-"
        with:
          path: |
            ${{ inputs.pip_cache_dir }}
            ${{ inputs.pre_commit_cache_dir }}
            ${{ inputs.curl_cache_dir }}
            ${{ steps.go-cache.outputs.dir }}
          key: "${{ env.BASE_CACHE_KEY }}\
            ${{ hashFiles('**/requirements-test.txt') }}-\
            ${{ hashFiles('**/requirements.txt') }}-\
            ${{ hashFiles('**/.pre-commit-config.yaml') }}"
          restore-keys: |
            ${{ env.BASE_CACHE_KEY }}
      - name: Setup curl cache
        run: mkdir -p ${{ inputs.curl_cache_dir }}
      - name: Install shfmt
        run: go install mvdan.cc/sh/v3/cmd/shfmt@${{ inputs.shfmt_version }}
      - name: Checkout source
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --requirement requirements-test.txt
      - name: Set up pre-commit hook environments
        run: pre-commit install-hooks
      - name: Run pre-commit on all files
        run: pre-commit run --all-files
